[en]
  title = "SpiffyGoose's Website"
  languageName = "English"
  weight = 1
  contentdir = "content/en"
[en.params]
  languagedir = "ltr"

  
[fr]
  title = "Le Site du SpiffyGoose"
  languageName = "Français"
  weight = 2
  contentdir = "content/fr"
[fr.params]
  languagedir = "ltr"

