[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 1

[[main]]
  identifier = "gallery"
  name = "Galerie"
  url = "gallery"
  weight = 2
  
[[main]]
  identifier = "notes"
  name = "Des Mots"
  url = "notes"
  weight = 3
  
[[main]]
  identifier = "archive"
  name = "Archives"
  url = "archive"
  weight = 4
  
[[main]]
  identifier = "about"
  name = "Sur"
  url = "about"
  weight = 5
